/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define APP_PHY_LINKUP_TIMEOUT_COUNT 800000U
#define APP_PHY_AUTONEGO_TIMEOUT_COUNT 800000U
#define APP_PHY_STABILITY_DELAY_US 500000U
#define APP_USER_DEFINED_MAC_ADDRESS 1
#define APP_MAC_ADDRESS {0x54, 0x27, 0x8d, 0x00, 0x00, 0x00}
#define APP_MAC_ADDRESS2 {0xd3, 0xbe, 0xd9, 0x45, 0x22, 0x60}
#define APP_ENET_QOS_BUFF_ALIGNMENT ENET_QOS_BUFF_ALIGNMENT
#define CONFIG_CPU_CORTEX_M 1
#define CONFIG_FLASH_BASE_ADDRESS 0x00400000
#define CONFIG_FLASH_DEFAULT_APP_OFFSET 0x0
#define CONFIG_HAS_FLASH_LOAD_OFFSET 1
#define CONFIG_FLASH_LOAD_OFFSET 0x0
#define CONFIG_UART_RETRY_TIMES 0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
