# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MCXE31B/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_board_boot_header true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_edma_soc true)
set(CONFIG_USE_driver_memory true)
set(CONFIG_USE_driver_siul2 true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_CMSIS true)
set(CONFIG_USE_device_system true)
set(CONFIG_USE_device_startup true)
set(CONFIG_USE_driver_cache_armv7_m7 true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_dmamux true)
set(CONFIG_USE_driver_edma4 true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_driver_qspi_mcxe31b true)
set(CONFIG_USE_driver_qspi_edma true)
set(CONFIG_USE_driver_qspi true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_CORE cm7f)
set(CONFIG_DEVICE MCXE31B)
set(CONFIG_BOARD frdmmcxe31b)
set(CONFIG_KIT frdmmcxe31b)
set(CONFIG_DEVICE_ID MCXE31B)
set(CONFIG_FPU SP_FPU)
set(CONFIG_DSP NO_DSP)
set(CONFIG_CORE_ID core0)
